// frontend/src/pages/InPlay.jsx
import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { MOCK_DATA } from '../data/mockData';
import BetSlip from '../components/BetSlip/BetSlip';
import OddsButton from '../components/Match/OddsButton';

export default function InPlay() {
    const { matchId } = useParams();
    const [betSlipOpen, setBetSlipOpen] = useState(false);
    const [selectedBet, setSelectedBet] = useState(null);

    // Get match data (in real app, would fetch from API)
    const match = MOCK_DATA.liveMatches[0]; // Default to first live match

    const handlePlaceBet = (selection, odds) => {
        setSelectedBet({
            matchId: match.matchId,
            match: `${match.teams.home.name} vs ${match.teams.away.name}`,
            league: match.league,
            selection,
            market: 'Match Winner',
            odds
        });
        setBetSlipOpen(true);
    };

    return (
        <div style={{ padding: '16px' }}>
            {/* Match Info Card */}
            <div className="card" style={{ marginBottom: '16px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                    <span className="badge badge-live">● LIVE</span>
                    <span style={{ fontSize: '12px', color: 'var(--color-text-muted)' }}>{match.matchId}</span>
                </div>
                <div style={{ fontSize: '14px', color: 'var(--color-text-muted)', marginBottom: '12px' }}>
                    {match.league}
                </div>

                {/* Teams and Scores */}
                <div style={{ display: 'grid', gap: '12px' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <span style={{ fontSize: '24px' }}>{match.teams.home.flag}</span>
                            <span style={{ fontWeight: 600, fontSize: '16px' }}>{match.teams.home.name}</span>
                        </div>
                        <div style={{ textAlign: 'right' }}>
                            <div style={{ fontSize: '20px', fontWeight: 700, color: 'var(--color-primary)' }}>
                                {match.teams.home.score}
                            </div>
                            <div style={{ fontSize: '12px', color: 'var(--color-text-muted)' }}>
                                {match.teams.home.overs}
                            </div>
                        </div>
                    </div>

                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <span style={{ fontSize: '24px' }}>{match.teams.away.flag}</span>
                            <span style={{ fontWeight: 600, fontSize: '16px' }}>{match.teams.away.name}</span>
                        </div>
                        <div style={{ textAlign: 'right' }}>
                            <div style={{ fontSize: '20px', fontWeight: 700, color: 'var(--color-primary)' }}>
                                {match.teams.away.score}
                            </div>
                            <div style={{ fontSize: '12px', color: 'var(--color-text-muted)' }}>
                                {match.teams.away.overs}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Match Winner Market */}
            <div className="card" style={{ marginBottom: '16px' }}>
                <h4 style={{ marginBottom: '12px', fontSize: '16px', fontWeight: 700 }}>Match Winner</h4>
                <div style={{ display: 'grid', gap: '12px' }}>
                    <OddsButton
                        selection={match.teams.home.name}
                        odds={match.odds.home.back}
                        onClick={() => handlePlaceBet(match.teams.home.name, match.odds.home.back)}
                    />
                    <OddsButton
                        selection={match.teams.away.name}
                        odds={match.odds.away.back}
                        onClick={() => handlePlaceBet(match.teams.away.name, match.odds.away.back)}
                    />
                </div>
            </div>

            {/* Session Runs */}
            <div className="card" style={{ marginBottom: '16px' }}>
                <h4 style={{ marginBottom: '12px', fontSize: '16px', fontWeight: 700 }}>Session Runs</h4>
                <div style={{ padding: '12px', background: 'var(--color-background)', borderRadius: '8px', textAlign: 'center' }}>
                    <div style={{ fontSize: '24px', fontWeight: 700, color: 'var(--color-primary)' }}>
                        {match.sessionRuns}
                    </div>
                    <div style={{ fontSize: '12px', color: 'var(--color-text-muted)', marginTop: '4px' }}>
                        Current Session
                    </div>
                </div>
            </div>

            {/* Match Stats */}
            <div className="card">
                <h4 style={{ marginBottom: '12px', fontSize: '16px', fontWeight: 700 }}>Match Stats</h4>
                <div style={{ display: 'grid', gap: '12px' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span style={{ color: 'var(--color-text-muted)', fontSize: '14px' }}>Top Batsman</span>
                        <span style={{ fontWeight: 600, fontSize: '14px' }}>{match.topBatsman}</span>
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span style={{ color: 'var(--color-text-muted)', fontSize: '14px' }}>Current Run Rate</span>
                        <span style={{ fontWeight: 600, fontSize: '14px' }}>{match.runRate.current}</span>
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span style={{ color: 'var(--color-text-muted)', fontSize: '14px' }}>Required Run Rate</span>
                        <span style={{ fontWeight: 600, fontSize: '14px' }}>{match.runRate.required}</span>
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span style={{ color: 'var(--color-text-muted)', fontSize: '14px' }}>Target Projection</span>
                        <span style={{ fontWeight: 600, fontSize: '14px' }}>{match.targetProjection}</span>
                    </div>
                </div>
            </div>

            <BetSlip
                isOpen={betSlipOpen}
                onClose={() => setBetSlipOpen(false)}
                bet={selectedBet}
            />
        </div>
    );
}

// frontend/src/routes/in-play/+page.svelte
<script>
    import OddsButton from '$lib/components/OddsButton.svelte';
    import BetSlip from '$lib/components/BetSlip.svelte';
    import { MOCK_DATA } from '$lib/data/mockData.js';
    import { formatters } from '$lib/utils/formatters.js';

    let match = $state(MOCK_DATA.liveMatches[0]);
    let showBetSlip = $state(false);
    let selectedBet = $state(null);

    function selectBet(selection, odds) {
        selectedBet = {
            matchId: match.matchId,
            match: `${match.teams.home.name} vs ${match.teams.away.name}`,
            league: match.league,
            selection,
            odds
        };
        showBetSlip = true;
    }
</script>

<div class="in-play-page">
    {#if match}
        <!-- Match Detail Card -->
        <div class="match-detail-card">
            <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:16px;">
                <span style="font-size:12px;color:var(--color-text-muted);">{match.league}</span>
                <span class="badge badge-live">
                    <span style="font-size:8px;margin-right:4px;">●</span> LIVE
                </span>
            </div>

            <div class="match-score-section">
                <div class="team-info">
                    <div class="team-flag">{match.teams.home.flag}</div>
                    <div style="font-weight:700;font-size:16px;">{match.teams.home.name}</div>
                    {#if match.teams.home.score}
                        <div style="font-size:24px;font-weight:800;color:var(--color-primary);margin-top:4px;">
                            {match.teams.home.score}
                        </div>
                        <div style="font-size:12px;color:var(--color-text-muted);">{match.teams.home.overs}</div>
                    {/if}
                </div>

                <div class="vs-badge">VS</div>

                <div class="team-info">
                    <div class="team-flag">{match.teams.away.flag}</div>
                    <div style="font-weight:700;font-size:16px;">{match.teams.away.name}</div>
                    {#if match.teams.away.score}
                        <div style="font-size:24px;font-weight:800;color:var(--color-primary);margin-top:4px;">
                            {match.teams.away.score}
                        </div>
                        <div style="font-size:12px;color:var(--color-text-muted);">{match.teams.away.overs}</div>
                    {/if}
                </div>
            </div>
        </div>

        <!-- Match Winner Odds -->
        <div style="margin-bottom:16px;">
            <h3 style="font-size:16px;font-weight:700;margin-bottom:12px;">Match Winner</h3>
            <div class="odds-row">
                <OddsButton
                    selection={match.teams.home.name}
                    odds={match.odds.home.back}
                    onclick={() => selectBet(match.teams.home.name, match.odds.home.back)}
                />
                <OddsButton
                    selection={match.teams.away.name}
                    odds={match.odds.away.back}
                    onclick={() => selectBet(match.teams.away.name, match.odds.away.back)}
                />
            </div>
        </div>

        <!-- Session & Stats -->
        {#if match.sessionRuns}
            <div style="margin-bottom:16px;">
                <h3 style="font-size:16px;font-weight:700;margin-bottom:12px;">Session & Stats</h3>
                <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;">
                    <div class="session-card">
                        <div style="font-size:12px;color:var(--color-text-muted);margin-bottom:4px;">Session Runs</div>
                        <div style="font-weight:700;color:var(--color-primary);">{match.sessionRuns}</div>
                    </div>
                    {#if match.topBatsman}
                        <div class="session-card">
                            <div style="font-size:12px;color:var(--color-text-muted);margin-bottom:4px;">Top Batsman</div>
                            <div style="font-weight:700;">{match.topBatsman}</div>
                        </div>
                    {/if}
                    {#if match.winProbability}
                        <div class="session-card">
                            <div style="font-size:12px;color:var(--color-text-muted);margin-bottom:4px;">Win Probability</div>
                            <div style="font-weight:700;color:var(--color-primary);">
                                {match.teams.home.name}: {match.winProbability.home}%
                            </div>
                        </div>
                    {/if}
                    {#if match.targetProjection}
                        <div class="session-card">
                            <div style="font-size:12px;color:var(--color-text-muted);margin-bottom:4px;">Target Projection</div>
                            <div style="font-weight:700;">{match.targetProjection}</div>
                        </div>
                    {/if}
                </div>
            </div>
        {/if}

        <!-- Run Rate -->
        {#if match.runRate}
            <div style="margin-bottom:16px;">
                <h3 style="font-size:16px;font-weight:700;margin-bottom:12px;">Run Rate</h3>
                <div style="display:flex;gap:16px;">
                    <div class="session-card" style="flex:1;">
                        <div style="font-size:12px;color:var(--color-text-muted);margin-bottom:4px;">Current RR</div>
                        <div style="font-weight:700;font-size:20px;color:var(--color-primary);">
                            {match.runRate.current}
                        </div>
                    </div>
                    <div class="session-card" style="flex:1;">
                        <div style="font-size:12px;color:var(--color-text-muted);margin-bottom:4px;">Required RR</div>
                        <div style="font-weight:700;font-size:20px;color:var(--color-warning);">
                            {match.runRate.required}
                        </div>
                    </div>
                </div>
            </div>
        {/if}
    {/if}
</div>

<BetSlip
    isOpen={showBetSlip}
    bet={selectedBet}
    onclose={() => showBetSlip = false}
/>
