// frontend/src/lib/components/OddsButton.svelte
<script>
    import { formatters } from '$lib/utils/formatters.js';

    let { selection = '', odds = 0, isActive = false, onclick } = $props();
</script>

<button
    class="odds-btn {isActive ? 'active' : ''}"
    onclick={onclick}
    style={isActive ? 'background:rgba(0,255,135,0.15);border-color:var(--color-primary);' : ''}
>
    <div class="odds-value">{formatters.odds(odds)}</div>
    <div class="odds-label">{selection}</div>
</button>

// frontend/src/components/Match/OddsButton.jsx
import { formatters } from '../../utils/formatters';

export default function OddsButton({ selection, odds, onClick, isActive }) {
    return (
        <button
            className={`odds-btn ${isActive ? 'active' : ''}`}
            onClick={onClick}
            style={isActive ? {
                background: 'rgba(0, 255, 135, 0.15)',
                borderColor: 'var(--color-primary)'
            } : {}}
        >
            <div className="odds-value">{formatters.odds(odds)}</div>
            <div className="odds-label">{selection}</div>
        </button>
    );
}
