// frontend/src/components/UI/Modal.jsx
export default function Modal({ isOpen, onClose, title, children }) {
    if (!isOpen) return null;

    return (
        <div className={`modal ${isOpen ? 'show' : ''}`} onClick={onClose}>
            <div className="modal-content" onClick={(e) => e.stopPropagation()}>
                <div className="modal-header">
                    <h3>{title}</h3>
                    <button className="close-modal" onClick={onClose}>×</button>
                </div>
                <div className="modal-body">
                    {children}
                </div>
            </div>
        </div>
    );
}

// frontend/src/lib/components/Modal.svelte
<script>
    let { isOpen = false, title = '', onclose, children } = $props();

    function handleBackdrop() {
        if (onclose) onclose();
    }

    function stopProp(e) {
        e.stopPropagation();
    }
</script>

{#if isOpen}
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div class="modal show" onclick={handleBackdrop}>
        <!-- svelte-ignore a11y_click_events_have_key_events -->
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div class="modal-content" onclick={stopProp}>
            <div class="modal-header">
                <h3>{title}</h3>
                <button class="close-modal" onclick={onclose}>×</button>
            </div>
            <div class="modal-body">
                {@render children()}
            </div>
        </div>
    </div>
{/if}
